#Manuscript: Host phylogeny and host ecology structure the mammalian gut microbiota 
#at different taxonomic scales
#Rojas et al. 2020
#Code for generating a matrix of divergence times between each pair of host species
#based on phylogenetic trees downloaded from: 
#Upham, N. S., J. A. Esselstyn, and W. Jetz. 2019. Inferring the mammal tree: species-level 
#sets of phylogenies for questions in ecology, evolution, and conservation. PLOS Biology. 

source(file="scripts/background.R"); #load necessary packages and specifications

#load metadata with baboon samples removed, as well as samples that did not amplify
load("data/sample_metadata_beta.Rdata");

#load nexus file generated by vertlife.org (1000 trees; DNA-only trees; artiodactyla & elephant)
#for exact configurations, see other/vertlife.config.yaml
trees <- ape::read.nexus("data/Upham2019_output.nex")

#get list of host species and create the pairs
spdf=metadf[!duplicated(metadf$species_short),]
spdf$tax_name=as.character(spdf$tax_name)
spdf[7,6] <- "Tragelaphus_oryx" ### rename Topi to match Upham 2019
spdf[9,6] <- "Giraffa_camelopardalis" ### drop the subspp to match Upham 2019
spdf$species_short
short <- spdf$species_short
taxa <- spdf$tax_name %>%  gsub(" ","_",.)
taxa_pairs <- combn(taxa,2,simplify=FALSE) 


#prune phylogenetic tree to only include host target species
plan(multisession)
master_matrix <- trees %>% furrr::future_map(function(j){
  ages <- taxa_pairs %>% map_dbl(function(i){ 
    j %>% getMRCA(.,tip = i) %>% 
      extract.clade(j,node = .) %>% 
      branching.times(.) %>% max(.,na.rm=T)
  })
  return(ages)
},.progress = TRUE)

#create matrix of pairwise divergence times
#these are the means across the 1,000 trees
mega_matrix <- master_matrix %>% furrr::future_map(function(x){
  age_matrix <- matrix(nrow = dim(spdf)[1],ncol = dim(spdf)[1],dimnames= list(short,short))
  age_matrix[lower.tri(age_matrix)] <- x
  age_matrix[upper.tri(age_matrix)] <- t(age_matrix)[upper.tri(age_matrix)]
  diag(age_matrix ) <- 0
  return(age_matrix)
},.progress=TRUE)
plan(sequential)

mega_matrix[[1]]
arr <- array( unlist(mega_matrix) , c(11,11,length(mega_matrix)))
divergence_times <- apply( arr , 1:2 , function(x) round(mean(x),5 ))
dimnames(divergence_times) <- list(short,short)

#save matrix of pairwise divergence times
save(divergence_times, file="data/host_divergence_times.Rdata") 

#calculate sd of mean divergence times
sd_div_times <- apply( arr , 1:2 , function(x) round(sd(x),5 ))
dimnames(sd_div_times) <- list(short,short)






