#Manuscript: Host phylogeny and host ecology structure the mammalian gut microbiota 
#at different taxonomic scales
#Rojas et al. 2020
#Code for generating obtaining gut microbiota alpha-diversity values from 4 metrics
#ASV richness, Chao 1 Richness, Shannon diversity, Simpson diversity, Faith's PD, Goods coverage

source(file="scripts/background.R"); #load necessary packages and specifications

##load ASV table generated by mothur software (Schloss et.al 2009)
#samples were subsampled to 17000 sequences; causing 23 samples to be removed 
masv=read.table("data/mothur.asvtable", sep="\t",header=T);

#clean up data 
masv$label=NULL; masv$numOtus=NULL;
rownames(masv)=masv$Group; masv$Group=NULL;

#replace ASV labels with ASV sequence names
#ASV sequence names are the column names of the ASV table output by DADA2
load("data/ASV_names.Rdata");
colnames(masv)=rownames(ASV)[match(names(masv),ASV$ASV)];
masv=as.matrix(masv);

#make a phyloseq object and then calculate richness and evenness with phyloseq
ps<- phyloseq(otu_table(masv, taxa_are_rows=FALSE));
alpha=estimate_richness(ps,split = TRUE, 
                        measures = c("Observed","Chao1","Shannon","Simpson"));

#calculate Good's coverage 
#append these values to the existing alpha diversity data frame
gcov=goods(masv);
alpha=merge(alpha, gcov, by=0, all=TRUE); 
colnames(alpha)[1]="Group";

#load phylogenetic tree of ASVs needed to calculate Faith's PD
#see script "get_phylotree_alpha.R" for how to generate
load("data/ASV_phylotree_alphadiv.Rdata"); #its name is fitGTR

#calculate Faith's phylogenetic diversity 
#append these values to the existing alpha diversity data frame
faith=pd(masv, phy_tree(fitGTR$tree), include.root=F);
faith$Group=row.names(faith);
alphadiv=merge(alpha, faith, by="Group");

#save data frame of alpha diversity metrics 
save(alphadiv, file="data/alphadiv_values.Rdata");
