#Manuscript: Host phylogeny and host ecology structure the mammalian gut microbiota 
#at different taxonomic scales
#Rojas et al. 2020
#Code for generating rarefaction curve of ASV richness
#NOTE: there will be a bit of a lag to run code from beginning to end
#because of large amount of data displayed

source(file="scripts/background.R"); #load necessary packages and specifications
#^^^also loads meta data

##load rarefaction data generated by mothur software (Schloss et.al 2009)
#samples were subsampled to 17000 sequences; causing 23 samples to be removed 
mothur_rarefaction=read.table("data/mothur.rarefaction", 
                              sep="\t", header=TRUE);

#clean up rarefaction curve data
raref=mothur_rarefaction[, grepl("X0.03.*",names(mothur_rarefaction))]; 
colnames(raref)=gsub("X0.03.", "", colnames(raref)); 

#remove baboon samples because not part of study
mysamples=as.character(meta$Group[meta$species_short!="Baboon"]);
raref=data.frame(raref[, (colnames(raref) %in% mysamples)]);
raref=cbind(mothur_rarefaction$numsampled,raref);
colnames(raref)[1]="numsampled";

#melt table for ggplot2 (timepoint|sample|numOTUs)
rf<- reshape2::melt(raref, id.vars="numsampled",value.name = "ASV_Richness");
colnames(rf)=c("TimeSampled", "Group", "ASV_Richness");
rare_meta=merge(rf, meta, by="Group");

#save color gradient (1 color for each host species)
my_col=c("#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462",
         "#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f");

#set tick marks for x-axis and y-axis
reads=seq(0, nrow(mothur_rarefaction), by=2500);
otus=seq(0, max(mothur_rarefaction[-1]), by=400);

#plot! 
rfc=ggplot(data=rare_meta) + 
  geom_line(mapping=aes(x=TimeSampled, 
                        y=ASV_Richness, 
                        col=species_short, 
                        group=Group))+ 
  scale_x_continuous(breaks=reads)+
  scale_y_continuous(breaks=otus)+ 
  scale_colour_manual(values=my_col)+
  labs(x = "Number of Reads",
       y = "ASV Richness",
       colour= "")+
  theme_bw() +
  guides(color=guide_legend(override.aes = list(size=3)))+
  theme(panel.background= element_rect(colour = "black", size=2),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position="right", 
        legend.text = element_text(size=14),
        axis.text.y = element_text(size=14),
        axis.title.y = element_text(size=14, face="bold"),
        axis.text.x = element_text(size=14),
        axis.title.x = element_text(size=14, face="bold"));

#plot(rfc);

# #save image 
#NOTE: there is a bit of a lag because of large amount of data displayed
ggsave(filename="rarefaction_curve.pdf",
       device="pdf",path="./figures",
       plot=rfc,
       width=9,
       height=6,
       units="in",
       dpi=500)